### PR TITLE
decided to add a picture where I look a bit happier.

### PR DESCRIPTION
**Pull request by scottcrawford03**

### CODE REVIEW

**Comment by worace** [comment]
@scottcrawford03 this has merge conflicts for some reason; is it still a valid change?

**Comment by scottcrawford03** [comment]
@worace I believe the merge conflict is because it's named the same thing as the previous image that I put in of myself.

**Comment by worace** [comment]
@scottcrawford03  can you update your local master and try merging it on your machine to see what happens?

**Comment by scottcrawford03** [comment]
@worace on my local it just replaced the file just fine.

**Pull request closed without merging**
